"""content posts carry text channels: replies, a platform-neutral title and url

Content Studio drafted only TikTok carousels, and the post row said so in two
column names. X and LinkedIn posts are words first, so the row becomes
platform-neutral rather than growing a second shape:

- replies — the author's own follow-ups under a post, in order: an X reply
  or thread, a LinkedIn first comment. Empty for every existing post.
- tiktok_title becomes title and tiktok_url becomes
  published_url: a title field and a link exist on most platforms, and a
  LinkedIn post's link in a column named for TikTok is a lie the next reader
  has to learn.

Renamed rather than dropped and re-added, so every stored value survives. The
renames sit inside batch_alter_table because the desktop sidecar runs this
on SQLite (db/migrate.py); on Postgres batch mode emits the plain ALTERs.

Hand-written rather than autogenerated: there is no local Postgres to diff
against, and autogenerate reads a rename as a drop plus an add. CI's
`alembic check` compares it with the model.

Revision ID: 290f4a3b4827
Revises: 5e7128ddc249
Create Date: 2026-09-28 00:00:00.000000
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '290f4a3b4827'
down_revision = '5e7128ddc249'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with op.batch_alter_table('content_posts') as batch:
        batch.add_column(
            sa.Column(
                'replies',
                sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
                nullable=False,
                server_default='[]',
            )
        )
        batch.alter_column('tiktok_title', new_column_name='title')
        batch.alter_column('tiktok_url', new_column_name='published_url')


def downgrade() -> None:
    with op.batch_alter_table('content_posts') as batch:
        batch.alter_column('published_url', new_column_name='tiktok_url')
        batch.alter_column('title', new_column_name='tiktok_title')
        batch.drop_column('replies')
