"""user_model_settings: the tier map and the fallback switch, server-side

The map shipped in localStorage and rode on each agent request, so the one run
that most needs it — the scheduled brief, which has no browser attached — could
never read it. A setting the user believes is global has to be global.

Autogenerated, then trimmed to this table. The rest of what autogenerate
proposed was drift between the dev database and today's models (nine
`content_posts` columns, `project_memories`' FTS index, two unique
constraints); shipping those drops would delete live columns on a database that
is simply ahead of this developer's copy.

Revision ID: 3867abd7b3e4
Revises: cf69496882c0
Create Date: 2026-09-08 20:36:15.811062
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import models.columns

# revision identifiers, used by Alembic.
revision = '3867abd7b3e4'
down_revision = 'cf69496882c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        'user_model_settings',
        # sa.Uuid(), not postgresql.UUID: the desktop sidecar runs this same
        # migration against SQLite.
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column(
            'tiers',
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
            nullable=False,
        ),
        sa.Column('auto_fallback', sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column('engine', sa.String(), server_default='', nullable=False),
        sa.Column('updated_at', models.columns.utc_datetime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id'),
    )


def downgrade() -> None:
    op.drop_table('user_model_settings')
