"""guest users: a real row for someone who has not signed in yet

Revision ID: a45b81fc1ae9
Revises: c3a9f1e7d2b4
Create Date: 2026-09-08 00:00:00.000000

Onboarding now runs an audit before anyone signs in, and everything that audit
produces — the project, the conversation, the report — lives in tables whose
owner column is NOT NULL. Rather than loosen those (every route-auth test would
grow a "no owner" branch, and the membership rule would stop being one rule), a
guest is a real ``users`` row with a synthetic email and an ``auth_identities``
row of provider ``guest`` keyed on the install id. Sign-in then links the Google
identity onto that row, or merges the guest into an existing account.

Two schema changes carry that:

* ``auth_identities.provider`` may now be ``guest`` (the install) and ``openai``
  (the ChatGPT account a subscription sign-in reveals — an identity hint that
  lets a later Google sign-in auto-merge, never a login on its own).
* ``oauth_states.link_user_id`` records which guest a sign-in should link to.
  The authorize endpoint is a browser navigation with no Authorization header,
  so the guest cannot present its token there; it presents a short-lived link
  code instead and the resolved user id rides the OAuth state through Google
  and back.

``batch_alter_table`` because the sidecar build runs this on SQLite, which
cannot drop a constraint in place.

Autogenerated for the column; the constraint swap is hand-written because
Alembic does not diff CHECK constraints, and the unrelated drift autogenerate
also reported (video columns, indexes present in the database but not the
models) was left out — it belongs to whichever change owns it.
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = 'a45b81fc1ae9'
down_revision = 'c3a9f1e7d2b4'
branch_labels = None
depends_on = None

_CHECK = 'ck_auth_identities_provider_allowed'


def upgrade() -> None:
    with op.batch_alter_table('auth_identities') as batch:
        batch.drop_constraint(_CHECK, type_='check')
        batch.create_check_constraint(_CHECK, "provider IN ('google', 'guest', 'openai')")
    op.add_column('oauth_states', sa.Column('link_user_id', sa.String(), nullable=True))


def downgrade() -> None:
    op.drop_column('oauth_states', 'link_user_id')
    with op.batch_alter_table('auth_identities') as batch:
        batch.drop_constraint(_CHECK, type_='check')
        batch.create_check_constraint(_CHECK, "provider IN ('google')")
