"""content posts keep their last pre-publish review

A founder publishing a carousel from Content Studio had no second opinion
before it went out. The agent now scores the post on six markers at weights
the server owns (agents/content/assessment.py) and stores the result here, so
the review survives a reload and shows in the publish dialog without a model
call. NULL until a post is reviewed; the checks in it are recomputed on every
read, so the column only has to hold what cannot be recomputed — the scores.

Hand-written rather than autogenerated: there is no local Postgres to diff
against. CI's `alembic check` compares it with the model.

Revision ID: b336354c84b5
Revises: b7c3e9a1d2f4
Create Date: 2026-09-25 00:00:00.000000
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b336354c84b5'
down_revision = 'b7c3e9a1d2f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        'content_posts',
        sa.Column(
            'last_assessment',
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
            nullable=True,
        ),
    )


def downgrade() -> None:
    op.drop_column('content_posts', 'last_assessment')
