"""model_usage: keep what each model call cost

Revision ID: cf69496882c0
Revises: a45b81fc1ae9
Create Date: 2026-09-08 00:00:00.000000

Duct already computes this per model call — tokens split by cached/fresh, plus a
dollar figure — and then drops it. The number reaches the browser as a live
``TOKEN_USAGE`` event that a reload forgets, and an OTel span bound for Sentry
where only an engineer can reach it. Under bring-your-own-key the user is the
one being billed, so "what did this cost me, on which model, for which agent"
was a question about their own money that Duct could not answer.

One row per model call rather than per run: a run fans out into subagents and a
summariser, and "what is actually expensive here" is a question about the shape
of the calls, not their sum.

``cost_micros`` is an integer, not a float. The page this feeds exists to be
trusted about money, and ``SUM()`` over binary floating point eventually renders
a total ending in 0.30000000000004. NULL where the price table does not know the
model, so the UI can show tokens without inventing a dollar figure — which is
what the live tooltip already does.

**Autogenerated, then trimmed to this table alone.** The full autogenerate diff
also wanted to drop nine `content_posts` columns, `content_plans.strategy`, the
`project_memories` FTS index, the `artifacts` project/slug index and two unique
constraints — drift between this dev database and models still in flight, none
of it this change's business and all of it destructive. Autogenerate is the
first draft the backend rules ask for; keeping only the table it found for the
model added here is the review they ask for next.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

from models.columns import utc_datetime

# revision identifiers, used by Alembic.
revision = "cf69496882c0"
down_revision = "a45b81fc1ae9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "model_usage",
        # sa.Uuid() rather than the postgresql dialect type: the desktop sidecar
        # runs this same metadata on SQLite.
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("conversation_id", sa.Uuid(), nullable=True),
        sa.Column("agent_type", sa.String(), server_default="", nullable=False),
        sa.Column("provider", sa.String(), server_default="", nullable=False),
        sa.Column("model", sa.String(), server_default="", nullable=False),
        sa.Column("tier", sa.String(), server_default="", nullable=False),
        sa.Column("scope", sa.String(), server_default="thread", nullable=False),
        sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cache_creation_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cost_micros", sa.BigInteger(), nullable=True),
        sa.Column("created_at", utc_datetime(), nullable=False),
        # SET NULL with the project, CASCADE with the user: deleting a project
        # must not erase what it already cost someone.
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_model_usage_conversation_id"), "model_usage", ["conversation_id"])
    op.create_index(op.f("ix_model_usage_created_at"), "model_usage", ["created_at"])
    op.create_index(op.f("ix_model_usage_project_id"), "model_usage", ["project_id"])
    # The two reads this table exists for. Both are always time-bounded, so the
    # timestamp belongs in the index rather than beside it.
    op.create_index("ix_model_usage_user_created", "model_usage", ["user_id", "created_at"])
    op.create_index("ix_model_usage_project_created", "model_usage", ["project_id", "created_at"])


def downgrade() -> None:
    op.drop_index("ix_model_usage_project_created", table_name="model_usage")
    op.drop_index("ix_model_usage_user_created", table_name="model_usage")
    op.drop_index(op.f("ix_model_usage_project_id"), table_name="model_usage")
    op.drop_index(op.f("ix_model_usage_created_at"), table_name="model_usage")
    op.drop_index(op.f("ix_model_usage_conversation_id"), table_name="model_usage")
    op.drop_table("model_usage")
