"""content post video and video model setting

Revision ID: e1ebd2525648
Revises: 290f4a3b4827
Create Date: 2026-09-29 22:26:22.203353

Video posts (issue #284). ``content_posts.video`` names the clip a video post
publishes and carries what the player shows; every take stays a
``content_assets`` row with a ``video/*`` type, so the takes need no column.
``user_model_settings.video_model`` is the saved pick for the Videos row, the
same kind of preference as ``image_model``: empty means whichever key can.

Not ``video_url`` / ``video_asset_id`` and the rest: a June branch that never
merged left columns by those names in one database, and reusing them would
make this migration fail there. Autogenerated against an empty Postgres built
from this lineage, so the diff holds only these two columns.
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1ebd2525648'
down_revision = '290f4a3b4827'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_posts', sa.Column('video', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('user_model_settings', sa.Column('video_model', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_model_settings', 'video_model')
    op.drop_column('content_posts', 'video')
    # ### end Alembic commands ###

