"""user_profile: the operator's name, role and voice, on the server

The profile lived in one browser's localStorage and travelled on each agent
request, so two devices disagreed and the scheduled brief — which has no
browser — read none of it. One row per user, every column optional, and an
absent row means what it meant before this table existed: Duct's default voice,
no name, and the language the person wrote in.

Autogenerated, then reduced to this table. The rest of the diff was the dev
database standing on branches that are not merged here (the video columns on
`content_posts`, `content_plans.strategy`, the FTS and lead-magnet indexes),
and applying it would have dropped live columns belonging to unshipped work.
Autogenerate is a first draft; this is the review it asks for.

Revision ID: f24e9528b320
Revises: c7e4a91b5d38
Create Date: 2026-09-13 11:17:32.633911
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

import models.columns

# revision identifiers, used by Alembic.
revision = 'f24e9528b320'
down_revision = 'c7e4a91b5d38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        'user_profile',
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('display_name', sa.String(), server_default='', nullable=False),
        sa.Column('role', sa.String(), server_default='', nullable=False),
        # Defaults to the shipped voice rather than to empty, so a row created
        # by saving only a name still describes a complete preference.
        sa.Column('writing_preset', sa.String(), server_default='practitioner', nullable=False),
        sa.Column('communication_language', sa.String(), server_default='', nullable=False),
        sa.Column('notes', sa.String(), server_default='', nullable=False),
        sa.Column('updated_at', models.columns._UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id'),
    )


def downgrade() -> None:
    op.drop_table('user_profile')
