"""Persistence helper — write generated bytes to the configured object store
(Cloudflare R2 in prod, local disk in dev) and insert a content_assets row
pointing at the public URL. See service/storage.py for the backend selection."""

from __future__ import annotations

import logging
from uuid import UUID, uuid4

from sqlmodel import Session

from models.content import ContentAsset
from service import storage
from agents.models import Provider
from service.images.schema import GeneratedImage, ImageAsset

logger = logging.getLogger(__name__)


# What ``content_assets.source`` records for a generated image. Gemini rows
# have said "gemini" since the column existed and the value is a plain string
# nothing re-validates, so the historical spelling stays; the other backends
# use their provider id.
_ASSET_SOURCE: dict[Provider, str] = {Provider.GOOGLE_GENAI: "gemini"}


def asset_source_for(provider: Provider) -> str:
    return _ASSET_SOURCE.get(provider, provider.value)


_MIME_TO_EXT = {
    "image/png":  "png",
    "image/jpeg": "jpg",
    "image/webp": "webp",
}


def persist_generated_image(
    project_id: UUID,
    image: GeneratedImage,
    *,
    db: Session,
    prompt: str,
    model:  str,
    params: dict,
    post_id: UUID | None = None,
    source:  str,
) -> ImageAsset:
    """Persist image bytes to object storage under
    projects/{project_id}/generated/<uuid>.<ext>, insert a ContentAsset row, and
    return an ImageAsset for the agent. The stored URL is absolute (R2 CDN) or
    relative (/uploads/... for the local backend) — the rest of the app treats
    it as an opaque public URL.

    `source` is recorded on the row: ``asset_source_for(provider)`` for a
    generated image, ``"upload"`` from the upload route.
    """
    ext = _MIME_TO_EXT.get(image.mime_type, "png")
    asset_id = uuid4()
    filename = f"{asset_id}.{ext}"
    key = f"projects/{project_id}/generated/{filename}"
    public_url = storage.put_image(key, image.data, image.mime_type)

    row = ContentAsset(
        id=asset_id,
        project_id=project_id,
        post_id=post_id,
        asset_type="generated",
        source=source,
        url=public_url,
        filename=filename,
        mime_type=image.mime_type,
        prompt=prompt,
        model=model,
        params=params,
    )
    db.add(row)
    db.commit()
    db.refresh(row)

    return ImageAsset(
        asset_id=row.id,
        url=public_url,
        mime_type=image.mime_type,
        prompt=prompt,
        model=model,
        params=params,
    )
