"""Persistence helper — write generated bytes to the Railway Volume and
insert a content_assets row pointing at the public URL."""

from __future__ import annotations

import logging
from pathlib import Path
from uuid import UUID, uuid4

from sqlmodel import Session

from config import get_configs
from models.content import ContentAsset
from service.gemini.schema import GeneratedImage, ImageAsset

logger = logging.getLogger(__name__)


_MIME_TO_EXT = {
    "image/png":  "png",
    "image/jpeg": "jpg",
    "image/webp": "webp",
}


def _uploads_dir() -> Path:
    """Resolve the uploads root from config; create if missing."""
    cfg = get_configs()
    base = Path(cfg.uploads_dir or "/app/uploads")
    base.mkdir(parents=True, exist_ok=True)
    return base


def persist_generated_image(
    project_id: UUID,
    image: GeneratedImage,
    *,
    db: Session,
    prompt: str,
    model:  str,
    params: dict,
    post_id: UUID | None = None,
    source:  str = "gemini",
) -> ImageAsset:
    """Write image bytes to /app/uploads/projects/{project_id}/generated/<uuid>.<ext>,
    insert a ContentAsset row, return an ImageAsset for the agent.

    `source` is recorded on the row; defaults to 'gemini' for the image
    service. Pass 'imagen' or 'upload' from the caller when appropriate.
    """
    base = _uploads_dir()
    proj_dir = base / "projects" / str(project_id) / "generated"
    proj_dir.mkdir(parents=True, exist_ok=True)

    ext = _MIME_TO_EXT.get(image.mime_type, "png")
    asset_id = uuid4()
    filename = f"{asset_id}.{ext}"
    path = proj_dir / filename
    path.write_bytes(image.data)
    logger.info("gemini: wrote %d bytes to %s", len(image.data), path)

    public_url = f"/uploads/projects/{project_id}/generated/{filename}"

    row = ContentAsset(
        id=asset_id,
        project_id=project_id,
        post_id=post_id,
        asset_type="generated",
        source=source,
        url=public_url,
        filename=filename,
        mime_type=image.mime_type,
        prompt=prompt,
        model=model,
        params=params,
    )
    db.add(row)
    db.commit()
    db.refresh(row)

    return ImageAsset(
        asset_id=row.id,
        url=public_url,
        mime_type=image.mime_type,
        prompt=prompt,
        model=model,
        params=params,
    )
