#!/usr/bin/env python3
"""Build the site's icon sprite from Lucide.

    python3 scripts/build_site_icons.py            # rewrites site/assets/icons.svg

The site has no build step and no webfonts, so icons are one SVG sprite that
every page references with `<svg class="ic"><use href="/assets/icons.svg#name"/></svg>`.
This script fetches each icon in ICONS from the pinned lucide-static release,
strips it to its paths and writes one `<symbol>` per icon. Add an icon by
adding its Lucide name here and re-running; hand-editing the sprite is how
two copies of the same icon end up disagreeing.

Lucide is ISC licensed (https://lucide.dev/license); the notice travels in the
sprite's first comment.
"""

import re
import sys
import urllib.request
from pathlib import Path

VERSION = "0.544.0"
BASE = f"https://unpkg.com/lucide-static@{VERSION}/icons/"
OUT = Path(__file__).resolve().parent.parent / "site" / "assets" / "icons.svg"

# Grouped by where the site uses them. Every name is a Lucide icon name.
ICONS = [
    # status
    "check", "x", "triangle-alert", "circle-check", "circle-x", "info",
    # navigation and actions
    "arrow-right", "arrow-down", "download", "external-link", "chevron-down",
    "play", "volume-2", "volume-x", "copy", "refresh-cw", "settings-2",
    # what Duct does
    "chart-column", "chart-line", "trending-up", "trending-down", "sparkles",
    "zap", "link", "plug", "search", "message-square", "mail", "bell-ring",
    "brain", "history", "shield-check", "key-round", "database", "server",
    "monitor", "git-branch", "scale", "file-text", "clipboard-list", "timer",
    "target", "magnet", "calculator", "pin", "map", "eye", "wallet",
    # audiences and jobs
    "megaphone", "sprout", "briefcase", "shopping-cart", "handshake", "rocket",
    "building-2", "pen-line", "headphones", "users", "user-round", "lightbulb",
    "clapperboard", "circle-help", "coins", "banknote", "mouse-pointer-click",
    "dollar-sign", "book-open", "code-2", "github", "layers", "compass",
]


def fetch(name: str) -> str:
    with urllib.request.urlopen(BASE + name + ".svg", timeout=20) as r:
        return r.read().decode("utf-8")


def symbol(name: str, svg: str) -> str:
    inner = re.search(r"<svg[^>]*>(.*?)</svg>", svg, re.S).group(1)
    inner = re.sub(r"\s+", " ", inner).strip()
    inner = re.sub(r"\s*/>", "/>", inner).replace("> <", "><")
    return f'<symbol id="{name}" viewBox="0 0 24 24">{inner}</symbol>'


def main() -> int:
    parts = []
    for name in ICONS:
        try:
            parts.append(symbol(name, fetch(name)))
        except Exception as exc:  # a typo in ICONS should fail loudly, not silently drop the icon
            print(f"{name}: {exc}", file=sys.stderr)
            return 1
    head = (
        '<svg xmlns="http://www.w3.org/2000/svg" style="display:none">\n'
        f"<!-- Lucide icons v{VERSION}, ISC licence, https://lucide.dev/license. "
        "Generated by scripts/build_site_icons.py; edit that list, not this file. -->\n"
    )
    OUT.write_text(head + "\n".join(parts) + "\n</svg>\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(OUT.parents[2])} with {len(parts)} icons")
    return 0


if __name__ == "__main__":
    sys.exit(main())
