"""Seedream (BytePlus ModelArk) text-to-image — a second image-gen provider
alongside Gemini.

REST, via httpx (no SDK dependency, consistent with our other service clients):
``POST /api/v3/images/generations`` returns a result image URL (or base64); we
download it to bytes. Mirrors SeedanceVideoClient (bytes out).

Its one job in our wiring: a face image generated by Seedream 5.0 Lite is a
TRUSTED ModelArk output, so it passes Seedance 2.0's input moderation (which
rejects every real-looking face from any other source, incl. Gemini). Text-to-image
only — references (image-to-image) are not wired here.

NOTE on `size`: Seedream requires the output to be at least 3,686,400 px. We map an
aspect ratio "a:b" to the smallest a*k × b*k that clears that floor, so 9:16 →
1440×2560, 16:9 → 2560×1440, etc. (Seedance can be called with ratio="adaptive" to
absorb any residual mismatch.)
"""

from __future__ import annotations

import base64
import logging
import math

from agents.models import ImageModel

logger = logging.getLogger(__name__)

DEFAULT_SEEDREAM_MODEL = ImageModel.SEEDREAM_5_0_LITE.value

_IMAGES_URL = "https://ark.ap-southeast.bytepluses.com/api/v3/images/generations"
_MIN_PIXELS = 3_686_400          # BytePlus floor for Seedream image size
_REQUEST_TIMEOUT_SECS = 120.0
_DOWNLOAD_TIMEOUT_SECS = 60.0


class SeedreamImageError(RuntimeError):
    """Raised on any Seedream failure (request / download)."""


def aspect_to_size(aspect_ratio: str) -> str:
    """Map an "a:b" aspect ratio to a "WxH" Seedream size clearing the pixel floor.
    Falls back to a 9:16 portrait when the ratio can't be parsed."""
    try:
        a_s, b_s = str(aspect_ratio).split(":")
        a, b = int(a_s), int(b_s)
        if a <= 0 or b <= 0:
            raise ValueError
    except (ValueError, AttributeError):
        a, b = 9, 16
    # smallest integer k with (a*k)*(b*k) >= floor → k = ceil(sqrt(floor/(a*b)))
    k = math.ceil(math.sqrt(_MIN_PIXELS / (a * b)))
    w, h = a * k, b * k
    # nudge each side up to an even number (friendlier for downstream encoders)
    w += w & 1
    h += h & 1
    return f"{w}x{h}"


class SeedreamImageClient:
    """Wraps the BytePlus ModelArk Seedream images REST API. One instance per
    request is fine (mirrors SeedanceVideoClient / GeminiImageClient)."""

    def __init__(self, api_key: str) -> None:
        if not api_key:
            raise ValueError("SeedreamImageClient: api_key is required")
        self._key = api_key

    async def generate_image(
        self,
        *,
        prompt: str,
        aspect_ratio: str = "9:16",
        number_of_images: int = 1,
        watermark: bool = False,
        output_format: str = "png",
        model: str = DEFAULT_SEEDREAM_MODEL,
    ) -> list[bytes]:
        """Generate `number_of_images` (1-4) independent images and return their raw
        bytes. Raises SeedreamImageError on failure."""
        import asyncio

        n = max(1, min(int(number_of_images or 1), 4))
        size = aspect_to_size(aspect_ratio)
        results = await asyncio.gather(
            *[self._one(prompt, size, watermark, output_format, model) for _ in range(n)]
        )
        return [b for b in results if b]

    async def _one(self, prompt, size, watermark, output_format, model) -> bytes:
        import httpx

        body = {
            "model": model,
            "prompt": prompt,
            "size": size,
            "output_format": output_format,
            "watermark": bool(watermark),
        }
        headers = {"Authorization": f"Bearer {self._key}", "Content-Type": "application/json"}
        async with httpx.AsyncClient(timeout=_REQUEST_TIMEOUT_SECS) as client:
            try:
                resp = await client.post(_IMAGES_URL, headers=headers, json=body)
                resp.raise_for_status()
            except httpx.HTTPStatusError as exc:
                err = {}
                try:
                    err = (exc.response.json() or {}).get("error") or {}
                except Exception:
                    pass
                detail = err.get("message") or exc.response.text[:300]
                if err.get("code") == "ModelNotOpen":
                    detail = (
                        f"model '{model}' isn't activated — enable it (and buy a resource "
                        "pack) in the BytePlus Ark Console, then retry."
                    )
                raise SeedreamImageError(
                    f"request failed ({exc.response.status_code}): {detail}"
                ) from exc
            except Exception as exc:
                raise SeedreamImageError(f"request failed: {exc}") from exc

            data = (resp.json() or {}).get("data") or []
            if not data:
                raise SeedreamImageError("no image in Seedream response.")
            item = data[0]
            if item.get("b64_json"):
                return base64.b64decode(item["b64_json"])
            url = item.get("url")
            if not url:
                raise SeedreamImageError("no url/b64_json in Seedream image result.")
            try:
                ir = await client.get(url, timeout=_DOWNLOAD_TIMEOUT_SECS, follow_redirects=True)
                ir.raise_for_status()
                out = ir.content
            except Exception as exc:
                raise SeedreamImageError(f"image download failed: {exc}") from exc
            if not out:
                raise SeedreamImageError("image downloaded empty.")
            return out
